### ISSUE TITLE
SET AFTER

### ISSUE THREAD

**Issue by 0xjona** [0xjona/litoranea#12]
- [ ] #17 Tre piedi e trave con mini americana (da service)
- [ ]  #20 Telo bianco (capirne le misure)
- [ ] #14 Materiale bituminoso o con paletti per struttura zolla
- [ ] #14 Giardino anomalo da faro (muschio etc.)
- [ ] #17 Illuminazione a cerchio per dj (chiedere al service)
- [ ] #17 2 led wall
