### ISSUE TITLE
STRUTTURA FASCI (TROVARE NOME)

### ISSUE THREAD

**Issue by 0xjona** [0xjona/litoranea#13]
- [ ] #16 Tubi innocenti (li procura Antonio da Marinero)
- [ ] #15 Giunti (da vedere lista Interclamp e li Antonio)
- [ ] #19 Plinti (chiedere a Dario per impresa edile che ci fa i getti su cerchi imof 50x50)
- [ ] Estremità circolare per fissare i fasci
- [ ] #20 Tessuti [chiamare o andare da La Tessil Casa (belpasso, via fondaco 5)]
